// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQR5eyghsaN2a0p-M3jidO9k7QpLufhuE',
    appId: '1:841318813415:web:32bae6937989c7695e5c42',
    messagingSenderId: '841318813415',
    projectId: 'salesapp-353fb',
    authDomain: 'salesapp-353fb.firebaseapp.com',
    storageBucket: 'salesapp-353fb.appspot.com',
    measurementId: 'G-MW4CHZ8MEK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQeiPIdpXkbf9oPijPX5kDzbOEs-hI_-w',
    appId: '1:841318813415:android:dec74fe334640e515e5c42',
    messagingSenderId: '841318813415',
    projectId: 'salesapp-353fb',
    storageBucket: 'salesapp-353fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaigwwJMFnmUeJt2qhD9XfnG_20lAuTuM',
    appId: '1:841318813415:ios:810a9854aa2966de5e5c42',
    messagingSenderId: '841318813415',
    projectId: 'salesapp-353fb',
    storageBucket: 'salesapp-353fb.appspot.com',
    iosBundleId: 'com.example.salesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaigwwJMFnmUeJt2qhD9XfnG_20lAuTuM',
    appId: '1:841318813415:ios:e55891c4be8524ea5e5c42',
    messagingSenderId: '841318813415',
    projectId: 'salesapp-353fb',
    storageBucket: 'salesapp-353fb.appspot.com',
    iosBundleId: 'com.example.salesApp.RunnerTests',
  );
}
